### ISSUE TITLE
Программный интерфейс v8Reader для открытия сравнения файлов из стороннего кода 1С

### ISSUE THREAD

**Issue by bambr1975** [xDrivenDevelopment/v8Reader#27]
Требуется открыть обработку из своей информационной базы, передав в нее программно нужные параметры и команды (а именно пути к двум своим обработкам и команду на сравнение двух этих обработок), при этом открывать отдельную информационную базу для сравнения не нужно.

**Comment by artbear** [comment]
Выполнено
