### ISSUE TITLE
Bug: при записи mxl2txt разложенный файл записывается в текущий каталог скрипта-запускатора

### ISSUE THREAD

**Issue by zeratulayuris** [xDrivenDevelopment/v8Reader#57]
Вот в этой строке https://github.com/xDrivenDevelopment/v8Reader/blob/43a987c5467d86d7bdf7e60cbcc76b19c87ce995/src/V8Reader/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/module.bsl#L4363 происходит запись файла по имени без расширения, т.е. полный путь к имени опускается и в итоге разложенный файл попадает в текущий каталог скрипта, вызвавшего v8Reader на исполнение.

**Comment by zeratulayuris** [comment]
Поясню - такое поведение возникает тогда, когда в параметрах указывается путь напрямую к mxl файлу, mxl в составе обработок прекрасно раскладываются туда, куда нужно.

**Comment by zeratulayuris** [comment]
@bambr1975 ping

**Comment by bambr1975** [comment]
Спасибо большое. Если вы не против, я ваш PR закрою, потому что ради изменения одной строки у меня 16 файлов, у вас 58. Вы ведь хотели переводить precommit1C на xml разборку?

**Comment by bambr1975** [comment]
Ой, вижу, 
>А заодно втащил разложенные mxl, использовав обновленный precommit1c.

подразумевается, что их тоже нужно втащить или наоборот?

**Comment by zeratulayuris** [comment]
Скорее наоборот, пусть будут изменения только в тех 16, которые у вас.

> Ой, вижу,
> 
> > А заодно втащил разложенные mxl, использовав обновленный precommit1c.
> 
> подразумевается, что их тоже нужно втащить или наоборот?

**Comment by zeratulayuris** [comment]
> Спасибо большое. Если вы не против, я ваш PR закрою, потому что ради изменения одной строки у меня 16 файлов, у вас 58. Вы ведь хотели переводить precommit1C на xml разборку?

Да, но с mxl это не очень выходит - конфигуратор их не сохранит в текст одной командой.

**Comment by zeratulayuris** [comment]
Работает )
